config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#index'
  get 'search', to: 'recipes#search'

  resources :recipes, only: %i[index show new create edit update approved rejected]

  resources :recipe_types, only: %i[show new create]
  resources :cuisines, only: %i[show new create]
  resources :recipe_lists, only: %i[show new create]
  resources :recipe_list_items, only: %i[create]
  
  get 'my_recipes', to: 'users#my_recipes'
  get 'my_lists', to: 'users#my_lists'
  get 'pending_recipes', to: 'users#pending_recipes'
  get 'recipe/:id/reject', to: 'users#reject_recipe', as: 'reject_recipe'
  get 'recipe/:id/approve', to: 'users#approve_recipe', as: 'approve_recipe'
  get 'all_recipes', to: 'recipes#all_recipes'
  delete 'recipe_list/:id/recipe/(.:recipe_id)', to: 'recipe_list_items#destroy', as: 'remove_from_list'

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :recipe_types, only: %i[show create]
      resources :recipes, only: %i[show create destroy]

      post 'recipes/:id/approve', to: 'recipes#approve', as: 'approve_recipe'
      post 'recipes/:id/reject', to: 'recipes#reject', as: 'reject_recipe'
    end
  end
end

app/models/recipe_list.rb
class RecipeList < ApplicationRecord
  has_many :recipe_list_items
  has_many :recipes, through: :recipe_list_items
  belongs_to :user

  validates :title, presence: true, uniqueness: {scope: :user}
end

app/controllers/recipe_lists_controller.rb
class RecipeListsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update]

  def show
    @recipe_list = RecipeList.find(params[:id])
    @recipe_list_items = @recipe_list.recipe_list_items
  end

  def new
    @recipe_list = RecipeList.new
  end

  def create
    @recipe_list = RecipeList.new(params.require(:recipe_list).permit(:title))
    @recipe_list.user = current_user
    if @recipe_list.save
      redirect_to @recipe_list
    else
      flash[:alert] = 'Você deve informar um nome único'
      render :new
    end
  end
end

app/views/recipe_lists/new.html.erb
<h2>Nova Lista</h2>

<% if @recipe_list.errors.any? %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<%= form_for @recipe_list do |form| %>
  <div class="form-group">
    <%= form.label :title , 'Título', class: "col-form-label" %><br>
    <%= form.text_field :title, class: "form-control col-auto" %>
  </div>
  
  <div class="form-group">
    <%= form.submit 'Criar lista', class: "btn btn-dark btn-sm" %>
  </div>
<% end %>

app/views/recipe_lists/show.html.erb
<h2><%= @recipe_list.title%></h2>
<p><small>Lista criada por <%= @recipe_list.user.email %></small></p>
<div class="row mt-2">
  <% if @recipe_list.recipe_list_items.any? %>
    <% @recipe_list_items.each do |r| %>
    <article class="col-sm-6 media" id="<%= r.id %>">
      <p>
        <%= image_tag r.recipe.recipe_photo, class: "float-left item-img rounded-circle" %>
        <div class="media-body">
          <h4><%= link_to r.recipe.title, r.recipe %></h4>
          <ul>
            <li><%= r.recipe.recipe_type.name %></li>
            <li><%= r.recipe.cuisine.name %></li>
            <li><%= r.recipe.difficulty %></li>
            <li><%= r.recipe.cook_time_min %></li>
          </ul>
          <p class="float-right">
            <% if current_user && current_user == @recipe_list.user %>
              <%= link_to "Excluir", remove_from_list_path(params[:id], r.recipe.id), method: 'delete', class: "btn btn-sm btn-danger"%>
            <% end %>
          </p>
        </div>
      </p>
    </article>
    <% end %>
  <% end %>
</div>