config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#index'
  get 'search', to: 'recipes#search'

  resources :recipes, only: %i[index show new create edit update approved rejected]

  resources :recipe_types, only: %i[show new create]
  resources :cuisines, only: %i[show new create]
  resources :recipe_lists, only: %i[show new create]
  resources :recipe_list_items, only: %i[create]
  
  get 'my_recipes', to: 'users#my_recipes'
  get 'my_lists', to: 'users#my_lists'
  get 'pending_recipes', to: 'users#pending_recipes'
  get 'recipe/:id/reject', to: 'users#reject_recipe', as: 'reject_recipe'
  get 'recipe/:id/approve', to: 'users#approve_recipe', as: 'approve_recipe'
  get 'all_recipes', to: 'recipes#all_recipes'
  delete 'recipe_list/:id/recipe/(.:recipe_id)', to: 'recipe_list_items#destroy', as: 'remove_from_list'

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :recipe_types, only: %i[show create]
      resources :recipes, only: %i[show create destroy]

      post 'recipes/:id/approve', to: 'recipes#approve', as: 'approve_recipe'
      post 'recipes/:id/reject', to: 'recipes#reject', as: 'reject_recipe'
    end
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :recipe_type
  belongs_to :cuisine
  belongs_to :user
  has_many :recipe_list_items
  has_one_attached :recipe_photo
  
  validates :title, :recipe_type_id, :cuisine_id, :difficulty, :cook_time, :ingredients, :cook_method, presence: true
  validates :title, uniqueness: true

  enum status: { pending: 0, approved: 5, rejected: 10 }

  def cook_time_min
    "#{cook_time} minutos"
  end
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes

  validates :name, presence: true, uniqueness: true
end

app/controllers/api/v1/recipes_controller.rb
class Api::V1::RecipesController < Api::V1::ApiController
  def create
    @recipe = Recipe.create(recipe_params)

    if @recipe.save
      render json: @recipe, status: 201
    else
      render json: { message: 'Erro ao salvar tipo de receita' }, status: 406
    end
  end

  def approve
    @recipe = Recipe.find(params[:id])
    @recipe.status = :approved

    render json: @recipe, except: %i[created_at], status: 202
  rescue ActiveRecord::RecordNotFound
    render json: {message: "ID inválido."}, status: 404
  end

  def reject
    @recipe = Recipe.find(params[:id])
    @recipe.status = :rejected

    render json: @recipe, except: %i[created_at], status: 202
  rescue ActiveRecord::RecordNotFound
    render json: {message: "ID inválido."}, status: 404
  end

  def show 
    @recipe = Recipe.find(params[:id])

    render json: {recipe: @recipe}, except: %i[created_at updated_at], status: 202, include: {recipes: {except: %i[created_at updated_at]}}
    
  rescue ActiveRecord::RecordNotFound
    render json: {message: "ID inválido."}, status: 404
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    render json: @recipe, status: 200

  rescue ActiveRecord::RecordNotFound
    render json: { message: "ID inválido."}, status: 404
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :difficulty, :recipe_type_id, :cuisine_id, :user_id, :recipe_photo, :cook_time, :cook_method, :ingredients, :status)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update add_to_list pending]

  def index
  	@recipes = Recipe.approved.last(6).reverse
    @recipe_types = RecipeType.all
    @cuisines = Cuisine.all
  end

  def all_recipes
    @recipes = Recipe.approved
  end

  def show
    @recipe = Recipe.find(params[:id])
    @user = current_user
    @recipe_lists = RecipeList.where(user: current_user)
    @recipe_list_item = RecipeListItem.new
  end

  def new
    @recipe = Recipe.new
    @recipe_types = RecipeType.all
    @cuisines = Cuisine.all
    @recipe_lists = RecipeList.where(user: current_user)
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to @recipe
    else
      flash[:alert] = 'Não foi possível salvar a receita'
      @recipe_types = RecipeType.all
      @cuisines = Cuisine.all
      @recipe_lists = RecipeList.where(user: current_user)
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @recipe_types = RecipeType.all
    @cuisines = Cuisine.all
    @recipe_lists = RecipeList.where(user: current_user)
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.status = :pending
    
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      flash[:alert] = 'Não foi possível salvar a receita'
      @recipe_types = RecipeType.all
      @cuisines = Cuisine.all      
      @recipe_lists = RecipeList.where(user: current_user)
      render :edit
    end
  end

  def search
    @recipes = Recipe.where("title LIKE ?", "%#{params[:busca]}%")
  end

  def add_to_list
    @recipe = Recipe.find(params[:id])
    @recipe_list_item = RecipeListItem.new(params.require(:recipe_list_item).permit(:recipe_list_id))
    @recipe_list_item.recipe = @recipe

    if @recipe_list_item.save
      flash[:notice]
    else
      flash[:alert] = 'Erro ao salvar lista'
    end
    redirect_to @recipe
  end

  def pending
    @recipes = Recipe.pending
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :recipe_type_id, :user_id, :cuisine_id, :difficulty, :cook_time, :ingredients, :cook_method, :recipe_photo)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<%= form_for @recipe do |form| %>
  <div class="form-group">
    <%= form.label :title , 'Título', class: "col-form-label" %><br>
    <%= form.text_field :title, class: "form-control col-auto" %>
  </div>
 
  <div class="form-group">
    <%= form.label :recipe_type_id, 'Tipo da Receita', class: "col-form-label" %>
    <%= form.collection_select :recipe_type_id, @recipe_types, :id, :name, class: "form-control col-auto" %>
  </div>

  <div class="form-group">
    <%= form.label :cuisine_id, 'Cozinha', class: "col-form-label" %>
    <%= form.collection_select :cuisine_id, @cuisines, :id, :name, class: "form-control col-auto" %>
  </div>

  <div class="form-group">
    <%= form.label :difficulty, 'Dificuldade', class: "col-form-label" %><br>
    <%= form.text_field :difficulty, class: "form-control col-auto" %>
  </div>

  <div class="form-group">
    <%= form.label :cook_time, 'Tempo de Preparo', class: "col-form-label" %><br>
    <%= form.number_field :cook_time, class: "form-control col-auto" %>
  </div>

  <div class="form-group">
    <%= form.label :ingredients, 'Ingredientes', class: "col-form-label" %><br>
    <%= form.text_area :ingredients, class: "form-control col-auto" %>
  </div>
 
  <div class="form-group">
    <%= form.label :cook_method, 'Como Preparar', class: "col-form-label" %><br>
    <%= form.text_area :cook_method, class: "form-control col-auto" %>
  </div>

  <div class="form-group">
    <%= form.label :recipe_photo, 'Enviar foto', class: "col-form-label"%>
    <%= form.file_field :recipe_photo, class: "form-control-file col-auto" %>
  </div>

  <div class="form-group">
    <%= form.submit 'Enviar', class: "btn btn-dark btn-sm" %>
  </div>
<% end %>

app/views/recipes/_item.html.erb
<% @recipes.each do |recipe| %>
  <article class="col-sm-6 float-left media">
    <p>
      <%= image_tag recipe.recipe_photo, class: "float-left item-img rounded-circle" %>
      <div class="media-body">
        <h4><%= link_to recipe.title, recipe %></h4>
        <ul>
          <li><%= recipe.recipe_type.name %></li>
          <li><%= recipe.cuisine.name %></li>
          <li><%= recipe.difficulty %></li>
          <li><%= recipe.cook_time_min %></li>
        </ul>
      </div>
    </p>
  </article>
<% end %>

app/views/recipes/_search.html.erb
<%= form_with(url: "/search", method: "get", local: true) do %>
  <div class="form-inline">
    <div class="form-group mx-auto">
      <span class="mr-sm-1"><%= text_field_tag :busca, nil, class: "form-control" %></span>
      <%= submit_tag 'Buscar', class: "btn btn-dark btn-sm" %>
    </div>
  </div>
<% end %>

app/views/recipes/all_recipes.html.erb
<h2>Todas as receitas</h2>

<ul>
  <% @recipes.each do |recipe| %>
    <li><%= link_to recipe.title, recipe %></li>
  <% end %>
</ul>

app/views/recipes/edit.html.erb
<h2>Editar receita</h2>

<%= render 'form' %>

app/views/recipes/index.html.erb
<h2>Últimas receitas cadastradas</h2>

<%= render 'item' %>

app/views/recipes/new.html.erb
<h2>Cadastrar receita</h2>

<%= render 'form' %>

app/views/recipes/search.html.erb
<h2>Receitas encontradas com  "<%= params[:busca] %>"</h2>

<% @recipes.each do |recipe| %>
  <ul>
    <li><%= link_to recipe.title, recipe %></li>
  </ul>
<% end %>

app/views/recipes/show.html.erb
<div class="row">
  <div class="col-8">
    <h2><%= @recipe.title %></h2>
    <p>
      <small>Receita enviada por <%= @recipe.user.email %>.</small>
        <% if @recipe.rejected? %>
          <span class="badge badge-pill badge-danger">Recusada</span>
        <% else %>
          <% if @recipe.pending? %>
            <span class="badge badge-pill badge-warning">Pendente</span>
          <% else %>
            <span class="badge badge-pill badge-success">Aprovada</span>
          <% end %>
        <% end %>
      </p>
  </div>

  <div class="col-4 text-right">
    <% if current_user && (current_user == @recipe.user || current_user.admin?) %>
      <%= link_to 'Editar', edit_recipe_path, class: "btn btn-dark btn-sm" %>
    <% end %>
    <% if current_user && current_user.admin? %>
      <%= link_to 'Aprovar', approve_recipe_path, class: "btn btn-success btn-sm" %>
      <%= link_to 'Rejeitar', reject_recipe_path, class: "btn btn-danger btn-sm" %>
    <% end%>
  </div>
</div>


<p>
  <% if @recipe.recipe_photo %>
    <%= image_tag @recipe.recipe_photo, class: "img-fluid" %>
  <% end %>
</p>

<h3>Detalhes</h3>
<p><strong>Tipo da Receita:</strong>
  <%= @recipe.recipe_type.name %></p>
<p><strong>Cozinha:</strong>
  <%= @recipe.cuisine.name %></p>
<p><strong>Dificuldade:</strong>
  <%= @recipe.difficulty %></p>
<p><strong>Tempo de Preparo:</strong>
  <%= @recipe.cook_time_min %></p>

<h3>Ingredientes</h3>
<p>
  <%= @recipe.ingredients %>
</p>

<h3>Como Preparar</h3>
<p>
  <%= @recipe.cook_method %>
</p>

<h3>Listas</h3>
<% if user_signed_in? && @user.recipe_lists.any? %>
  <%= form_with model: @recipe_list_item do |form| %>
    <div class="form-group mx-auto">
      <span class="mr-sm-1"><%= form.label :recipe_list_id, "Adicionar a" %></span>
      <span class="mr-sm-1"><%= form.collection_select(:recipe_list_id, @recipe_lists, :id, :title) %></span>
      <%= form.hidden_field :recipe_id, value: params[:id] %>
      <%= form.submit "Salvar", class: "btn btn-dark btn-sm" %>
    </div>
  <% end %>
<% end %>

<% if flash[:failure] %>
  <div class="alert alert-secondary">
    <%= flash[:failure] %>
  </div>
<% end %>

<% if @recipe.recipe_list_items.any? %>
  <p>Salva em:
    <ul>
      <% @recipe.recipe_list_items.each do |r| %>
        <li><%= link_to r.recipe_list.title, r.recipe_list %></li>
      <% end %>
    </ul>
  </p>
<% else %>
  <p>Não está em nenhuma lista.</p>
<% end %>

<p class="text-center">
  <%= link_to 'Voltar', root_path, class: "btn btn-secondary btn-sm" %>
</p>