config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#index'
  get 'search', to: 'recipes#search'

  resources :recipes, only: %i[index show new create edit update approved rejected]

  resources :recipe_types, only: %i[show new create]
  resources :cuisines, only: %i[show new create]
  resources :recipe_lists, only: %i[show new create]
  resources :recipe_list_items, only: %i[create]
  
  get 'my_recipes', to: 'users#my_recipes'
  get 'my_lists', to: 'users#my_lists'
  get 'pending_recipes', to: 'users#pending_recipes'
  get 'recipe/:id/reject', to: 'users#reject_recipe', as: 'reject_recipe'
  get 'recipe/:id/approve', to: 'users#approve_recipe', as: 'approve_recipe'
  get 'all_recipes', to: 'recipes#all_recipes'
  delete 'recipe_list/:id/recipe/(.:recipe_id)', to: 'recipe_list_items#destroy', as: 'remove_from_list'

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :recipe_types, only: %i[show create]
      resources :recipes, only: %i[show create destroy]

      post 'recipes/:id/approve', to: 'recipes#approve', as: 'approve_recipe'
      post 'recipes/:id/reject', to: 'recipes#reject', as: 'reject_recipe'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes
  has_many :recipe_lists 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update my_recipes my_lists pending_recipes]
  before_action :verify_admin, only: %i[approved rejected]

  def my_recipes
    @recipes = Recipe.where(user: current_user)
    flash.now[:failure] = 'Você não tem receitas cadastradas ainda.'
  end

  def my_lists
    @recipe_lists = RecipeList.where(user: current_user)
    flash.now[:failure] = 'Você não tem listas cadastradas ainda.'
  end

  def pending_recipes
    if current_user.admin?
      @recipes = Recipe.where(status: :pending)
    else
      @recipes = Recipe.where(status: :pending, user: current_user)
    end
    flash.now[:failure] = 'Você não tem receitas pendentes.'
  end

  def approve_recipe
    Recipe.find(params[:id]).approved!
    flash[:notice] = 'Receita aprovada com sucesso'
    redirect_to pending_recipes_path
  end

  def reject_recipe
    Recipe.find(params[:id]).rejected!
    flash[:notice] = 'Receita rejeitada com sucesso'
    redirect_to pending_recipes_path
  end

  private

  def verify_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/views/users/_admin.html.erb
<hr>

<h3>Administrador</h3>
<p>Ações:
  <ul>
    <li><%= link_to 'Criar tipo de receita', new_recipe_type_path %></li>
    <li><%= link_to 'Criar cozinha', new_cuisine_path %></li>
  </ul>
</p>

<hr>

app/views/users/my_lists.html.erb
<h2>Minhas listas de receita</h2>
<p>
  <%= link_to 'Criar nova lista', new_recipe_list_path, class: "btn btn-success btn-sm" %>
</p>

<% if @recipe_lists.any? %>
  <ul>
    <% @recipe_lists.each do |recipe_list| %>
      <li><%= link_to recipe_list.title, recipe_list %></li>
    <% end %>
  </ul>
<% else %>
  <div class="alert alert-secondary">
    <%= flash[:failure] %>
  </div>
<% end %>

app/views/users/my_recipes.html.erb
<h2>Minhas receitas cadastradas</h2>

<% if @recipes.any? %>
  <%= render 'recipes/item' %>
<% else %>
  <div class="alert alert-secondary">
    <%= flash[:failure] %>
  </div>
<% end %>

app/views/users/pending_recipes.html.erb
<h2>Receitas pendentes</h2>
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if @recipes.any? %>
  <ul>
    <% @recipes.each do |recipe| %>
        <li><%= link_to recipe.title, recipe %></li>
    <% end %>
  </ul>
<% else %>
  <div class="alert alert-secondary">
    <%= flash[:failure] %>
  </div>
<% end %>