config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#index'
  get 'search', to: 'recipes#search'

  resources :recipes, only: %i[index show new create edit update approved rejected]

  resources :recipe_types, only: %i[show new create]
  resources :cuisines, only: %i[show new create]
  resources :recipe_lists, only: %i[show new create]
  resources :recipe_list_items, only: %i[create]
  
  get 'my_recipes', to: 'users#my_recipes'
  get 'my_lists', to: 'users#my_lists'
  get 'pending_recipes', to: 'users#pending_recipes'
  get 'recipe/:id/reject', to: 'users#reject_recipe', as: 'reject_recipe'
  get 'recipe/:id/approve', to: 'users#approve_recipe', as: 'approve_recipe'
  get 'all_recipes', to: 'recipes#all_recipes'
  delete 'recipe_list/:id/recipe/(.:recipe_id)', to: 'recipe_list_items#destroy', as: 'remove_from_list'

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :recipe_types, only: %i[show create]
      resources :recipes, only: %i[show create destroy]

      post 'recipes/:id/approve', to: 'recipes#approve', as: 'approve_recipe'
      post 'recipes/:id/reject', to: 'recipes#reject', as: 'reject_recipe'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="assets/stylesheets/recipes.scss">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <header class="col-sm-12 mt-3 ml-3">
          <h1 class="logo"><%= link_to 'CookBook', root_path %></h1>
          <p>Aqui você encontra as melhores receitas da internet. :)</p>
        </header>
      </div>

      <div class="row">
        <nav class="col-sm-3 text-left">
          <% if user_signed_in? %>
            <p>Olá, <%= current_user.email %>!</p>
          <% end %>
        </nav>

        <nav class="col-sm-9 text-right">
          <ul class="nav nav-pills justify-content-end">
            <% if user_signed_in? %>
              <li class="nav-item"><%= link_to 'Enviar uma receita', new_recipe_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to 'Receitas pendentes', pending_recipes_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to 'Minhas Receitas', my_recipes_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to 'Minhas Listas', my_lists_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to 'Sair', destroy_user_session_path, method: :delete, class: "nav-link" %></li>
            <% else %>
              <li class="nav-item"><%= link_to 'Entrar', new_user_session_path, class: "nav-link" %></li>
            <% end %>
          </ul>
        </nav>
      </div>

      <div class="row mt-3">
        <aside class="col-sm-4">
          <% if current_user && current_user.admin? %>
            <%= render 'users/admin' %>
          <% end %>                   
          <h4>Ver receitas</h4>
          <p>
            <%= link_to 'Todas as receitas', all_recipes_path %>
            <%= render 'recipes/search' %>
          </p>
          <p>
            <h5>Por tipo:</h5>
            <p>
              <%= render 'recipe_types/list' %>
            </p>
            <h5>Por cozinha:</h5>
            <p>
              <%= render 'cuisines/list' %>
            </p>
          </p>
        </aside>

        <main class="col-sm-8">
          <%= yield %>
        </main>
      </div>

      <div class="row">
        <footer class="col-sm-12">
          <hr>
          <p><h4>CookBook©</h4> 2019 - Todos os direitos reservados.</p>
        </footer>
      </div>
    </div>
  </body>
</html>